services:
  - type: web
    name: resume-sorter
    env: node
    plan: free
    buildCommand: npm install && npm install --prefix client && npm run build --prefix client && npm install --prefix server
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://chaithanya3021_db_user:chaithanya3021@cluster0.irvxemb.mongodb.net/Resume_sorter?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: resumesort_secret_2024
      - key: EMAIL_USER
        value: chaithanya3021@gmail.com
      - key: EMAIL_PASS
        value: tzrrmhzyveliqjcj
